export {default as PostCard } from './PostCard';
export {default as Categories } from './Categories';
export {default as PostWidget } from './PostWidget';
export {default as Header } from './Header';
export {default as Layout } from './Layout';
export {default as PostDetail } from './PostDetail';
export {default as Author } from './Author';
export {default as Footer} from './Footer';
export {default as HeadSection} from './HeadSection';
export {default as Company} from './Company';
export {default as Partners} from './Partners';
export {default as Features} from './Features';
export {default as CTAComponent} from './CTAComponent';
export {default as HeadComponent} from './CompanyComponents/HeadComponent';
// export {default as DeviderComponent} from './CompanyComponents/DividerComponent'
 export {default as ContentComponent} from './CompanyComponents/ContentComponent';
 export {default as CardComponent} from './CompanyComponents/CardComponent';
 export {default as SecondContent} from './CompanyComponents/SecondContent';
 export {default as TeamComponent} from './CompanyComponents/TeamComponent';
export {default as CompanyFeatures} from './CompanyComponents/CompanyFeatures';
export {default as HeadProject} from './ProjectComponent/HeadProject';